name: Automated Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
